name: Automatic Backporting

on:
  issue_comment:
    types: [created]

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        env:
          COMMENT: ${{ toJSON(github.event.comment) }}
        run: |
          echo "github.event.issue.pull_request:  ${{ github.event.issue.pull_request }}"
          echo "github.event.issue.pull_request.merged_at: ${{ github.event.issue.pull_request.merged_at }}"
          echo "github.event.comment: $COMMENT"
